### ISSUE TITLE
Missing call statements

### ISSUE THREAD

**Issue by bwerdeha** [oasp/oasp-vscode-ide#1]
I had to add "call" before each line in order to run the batch file properly.
If not, only the first "code" command will be executed.

**Comment by sjimenez77** [comment]
If you refer to the batch file for  windows is already tested and runs properly. Please review your Visual Studio Code configuration and set the correct PATH to run `code` within your terminal. Please visit https://code.visualstudio.com/docs/editor/command-line for further details.

Anyway, the recommended way to install the plugins is using Sync Settings plugin https://github.com/oasp/oasp-vscode-ide#install-extensions-with-sync-settings

**Comment by sjimenez77** [comment]
Due to lack of activity, I close the issue.
